osx_image: xcode9
language: objective-c

before_install:
  - brew update
  - gem install cocoapods --pre
install: echo "<3"
env:
  - MODE=build
script: ./travis-build.sh $MODE

# whitelist
branches:
  only:
    - master
